### ISSUE TITLE
Version 0.3 To-Do list

### ISSUE THREAD

**Issue by SamuiNe** [SamuiNe/Sophia-py#15]
#### Bot Stuffs
- [ ] Add ability to kick channel (Manager and bot owner)
- [ ] Add ability to delete tunnel room (Bot owner)
- [ ] Add ability to set tunnelmode defaults (Manager and bot owner)
- [ ] Add ability to restrict tunnelmode (Manager and bot owner)
- [ ] Add ability to ban server and channels from linking and creating tunnel room (Bot owner)
- [ ] Add ability to ban user from using tunnel room and global chat (Bot owner)
- [ ] Add ability to allow multiple manager positions in a tunnel room (Manager and bot owner)
- [x] ~~Add and implement rethinkdb to store essential bot data~~ _Maybe at Version 0.5_
- [x] Add try except finally in case of token does not exist, with an option to prompt manual filename input
- [x] ~~Add suggest command for user suggestions~~ _Maybe Version 0.6?_
- [x] ~~Add suggestresponse command for user suggestion response~~ _Maybe Version 0.6?_
- [x] ~~Add suggestdelete command for deleting user suggestion~~ _Maybe Version 0.6?_
- [x] ~~Add suggestfinalize command to finalize user suggestion~~ _Maybe Version 0.6?_
- [x] ~~Add suggestedit command for editing user suggestion~~ _Maybe Version 0.6?_
- [x] Add better exception handling and use traceback.print_exc()
- [x] Add random string output when an exception is handled
- [ ] Add Documentation
- [x] Simplify chat_tunnel.py code
#### Other Stuffs
- [ ] Create a website for Sophia
